name: Laravel

on:
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update composer
      run: composer update
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install node dependencies
      run: npm ci
    - name: Setup Project
      run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          npm run build
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test
